name: Deploy to Azure

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'
      - 'GitGitGadget/**'

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    if: github.event.repository.fork == false
    environment: deploy-to-azure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTION_NAME || 'GitGitGadget' }}
          respect-funcignore: true
